### PR TITLE
crud roles

### PR DESCRIPTION
**Pull request by javymarmol**
Creación modulo de Roles

### CODE REVIEW

**Review by sd8956 — APPROVED** [review]
Lo veo bien

**Review by musartedev — APPROVED** [review]
Buen trabajo, @javymarmol. Si se puede al subir un PR dejemos un pequeño video para ver que todo esté funcionando ok.

Excelente.

**Comment by javymarmol** [comment]
Gracias por la observacion @musenberg404, se los los comparto.

# API

## Requests

### **GET** - /api/roles

#### CURL

```sh
curl -X GET "http://localhost:8000/api/roles" \
    -H "Accept: application/json"
```

#### Header Parameters

- **Accept** should respect the following schema:

```
{
  "type": "string",
  "enum": [
    "application/json"
  ],
  "default": "application/json"
}
```

### **GET** - /api/roles/5f190810392bc52f9e78f6d1

#### CURL

```sh
curl -X GET "http://localhost:8000/api/roles/5f190810392bc52f9e78f6d1" \
    -H "Accept: application/json"
```

#### Header Parameters

- **Accept** should respect the following schema:

```
{
  "type": "string",
  "enum": [
    "application/json"
  ],
  "default": "application/json"
}
```

### **POST** - /api/roles

#### CURL

```sh
curl -X POST "http://localhost:8000/api/roles" \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTU0NzQ0MjIsImV4cCI6MTU5NTQ3NjIyMn0.sB-U5YIHyqqMnmU0oAtr2Fgo0RnRMFRz9Ro-W52tibE" \
    --data-raw "$body"
```

#### Header Parameters

- **Accept** should respect the following schema:

```
{
  "type": "string",
  "enum": [
    "application/json"
  ],
  "default": "application/json"
}
```
- **Content-Type** should respect the following schema:

```
{
  "type": "string",
  "enum": [
    "application/json"
  ],
  "default": "application/json"
}
```
- **Authorization** should respect the following schema:

```
{
  "type": "string",
  "enum": [
    "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTU0NzQ0MjIsImV4cCI6MTU5NTQ3NjIyMn0.sB-U5YIHyqqMnmU0oAtr2Fgo0RnRMFRz9Ro-W52tibE"
  ],
  "default": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTU0NzQ0MjIsImV4cCI6MTU5NTQ3NjIyMn0.sB-U5YIHyqqMnmU0oAtr2Fgo0RnRMFRz9Ro-W52tibE"
}
```

#### Body Parameters

- **body** should respect the following schema:

```
{
  "type": "string",
  "default": "{\"name\":\"test2\",\"description\":\"test2\"}"
}
```

### **PUT** - /api/roles/5f190810392bc52f9e78f6d1

#### CURL

```sh
curl -X PUT "http://localhost:8000/api/roles/5f190810392bc52f9e78f6d1" \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTU0NzYyODIsImV4cCI6MTU5NTQ3ODA4Mn0.gm3_jcEFU2ZXQhQ6R6caIP8FMkom6IosWj42XMkCEpA" \
    --data-raw "$body"
```

#### Header Parameters

- **Accept** should respect the following schema:

```
{
  "type": "string",
  "enum": [
    "application/json"
  ],
  "default": "application/json"
}
```
- **Content-Type** should respect the following schema:

```
{
  "type": "string",
  "enum": [
    "application/json"
  ],
  "default": "application/json"
}
```
- **Authorization** should respect the following schema:

```
{
  "type": "string",
  "enum": [
    "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTU0NzYyODIsImV4cCI6MTU5NTQ3ODA4Mn0.gm3_jcEFU2ZXQhQ6R6caIP8FMkom6IosWj42XMkCEpA"
  ],
  "default": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTU0NzYyODIsImV4cCI6MTU5NTQ3ODA4Mn0.gm3_jcEFU2ZXQhQ6R6caIP8FMkom6IosWj42XMkCEpA"
}
```

#### Body Parameters

- **body** should respect the following schema:

```
{
  "type": "string",
  "default": "{\"name\":\"updated\",\"description\":\"updated role\"}"
}
```

### **DELETE** - /api/roles/5f1907b41d39312d29f0bbc1

#### CURL

```sh
curl -X DELETE "http://localhost:8000/api/roles/5f1907b41d39312d29f0bbc1" \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTU0NzYyODIsImV4cCI6MTU5NTQ3ODA4Mn0.gm3_jcEFU2ZXQhQ6R6caIP8FMkom6IosWj42XMkCEpA" \
    --data-raw "$body"
```

#### Header Parameters

- **Accept** should respect the following schema:

```
{
  "type": "string",
  "enum": [
    "application/json"
  ],
  "default": "application/json"
}
```
- **Content-Type** should respect the following schema:

```
{
  "type": "string",
  "enum": [
    "application/json"
  ],
  "default": "application/json"
}
```
- **Authorization** should respect the following schema:

```
{
  "type": "string",
  "enum": [
    "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTU0NzYyODIsImV4cCI6MTU5NTQ3ODA4Mn0.gm3_jcEFU2ZXQhQ6R6caIP8FMkom6IosWj42XMkCEpA"
  ],
  "default": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTU0NzYyODIsImV4cCI6MTU5NTQ3ODA4Mn0.gm3_jcEFU2ZXQhQ6R6caIP8FMkom6IosWj42XMkCEpA"
}
```

#### Body Parameters

- **body** should respect the following schema:

```
{
  "type": "string",
  "default": "{}"
}
```

### **POST** - /api/auth/token

#### CURL

```sh
curl -X POST "http://localhost:8000/api/auth/token" \
    -H "Accept: application/json"
```

#### Header Parameters

- **Accept** should respect the following schema:

```
{
  "type": "string",
  "enum": [
    "application/json"
  ],
  "default": "application/json"
}
```

**Comment by javymarmol** [comment]
Acá dejo otra forma de ver los endpoints.

## Get all roles

**Endpoint**: GET - http://localhost:8000/api/roles

**Description**: N/A

#### Header
```
{
	Accept: application/json
}
```


#### Body
```

```

## Get role by ID

**Endpoint**: GET - http://localhost:8000/api/roles/5f190810392bc52f9e78f6d1

**Description**: N/A

#### Header
```
{
	Accept: application/json
}
```


#### Body
```

```

## Create Rol

**Endpoint**: POST - http://localhost:8000/api/roles

**Description**: N/A

#### Header
```
{
	Accept: application/json
	Content-Type: application/json
	Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTU0NzQ0MjIsImV4cCI6MTU5NTQ3NjIyMn0.sB-U5YIHyqqMnmU0oAtr2Fgo0RnRMFRz9Ro-W52tibE
}
```


#### Body
```
{
	"name": "test2",
	"description": "test2"
}
```

## Update role

**Endpoint**: PUT - http://localhost:8000/api/roles/5f190810392bc52f9e78f6d1

**Description**: N/A

#### Header
```
{
	Accept: application/json
	Content-Type: application/json
	Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTU0NzYyODIsImV4cCI6MTU5NTQ3ODA4Mn0.gm3_jcEFU2ZXQhQ6R6caIP8FMkom6IosWj42XMkCEpA
}
```


#### Body
```
{
	"name": "updated",
	"description": "updated role"
}
```

## Delete role

**Endpoint**: DELETE - http://localhost:8000/api/roles/5f1907b41d39312d29f0bbc1

**Description**: N/A

#### Header
```
{
	Accept: application/json
	Content-Type: application/json
	Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTU0NzYyODIsImV4cCI6MTU5NTQ3ODA4Mn0.gm3_jcEFU2ZXQhQ6R6caIP8FMkom6IosWj42XMkCEpA
}
```


#### Body
```
{}
```

## token

**Endpoint**: POST - http://localhost:8000/api/auth/token

**Description**: N/A

#### Header
```
{
	Accept: application/json
}
```


#### Body
```

```

**Pull request merged**
